export const countries = [
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', phone: '+93' },
  { name: 'Albania', code: 'AL', currency: 'ALL', phone: '+355' },
  { name: 'Algeria', code: 'DZ', currency: 'DZD', phone: '+213' },
  { name: 'Andorra', code: 'AD', currency: 'EUR', phone: '+376' },
  { name: 'Angola', code: 'AO', currency: 'AOA', phone: '+244' },
  { name: 'Antigua and Barbuda', code: 'AG', currency: 'XCD', phone: '+1-268' },
  { name: 'Argentina', code: 'AR', currency: 'ARS', phone: '+54' },
  { name: 'Armenia', code: 'AM', currency: 'AMD', phone: '+374' },
  { name: 'Australia', code: 'AU', currency: 'AUD', phone: '+61' },
  { name: 'Austria', code: 'AT', currency: 'EUR', phone: '+43' },
  { name: 'Azerbaijan', code: 'AZ', currency: 'AZN', phone: '+994' },
  { name: 'Bahamas', code: 'BS', currency: 'BSD', phone: '+1-242' },
  { name: 'Bahrain', code: 'BH', currency: 'BHD', phone: '+973' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', phone: '+880' },
  { name: 'Barbados', code: 'BB', currency: 'BBD', phone: '+1-246' },
  { name: 'Belarus', code: 'BY', currency: 'BYN', phone: '+375' },
  { name: 'Belgium', code: 'BE', currency: 'EUR', phone: '+32' },
  { name: 'Belize', code: 'BZ', currency: 'BZD', phone: '+501' },
  { name: 'Benin', code: 'BJ', currency: 'XOF', phone: '+229' },
  { name: 'Bhutan', code: 'BT', currency: 'BTN', phone: '+975' },
  { name: 'Bolivia', code: 'BO', currency: 'BOB', phone: '+591' },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: 'BAM', phone: '+387' },
  { name: 'Botswana', code: 'BW', currency: 'BWP', phone: '+267' },
  { name: 'Brazil', code: 'BR', currency: 'BRL', phone: '+55' },
  { name: 'Brunei', code: 'BN', currency: 'BND', phone: '+673' },
  { name: 'Bulgaria', code: 'BG', currency: 'BGN', phone: '+359' },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', phone: '+226' },
  { name: 'Burundi', code: 'BI', currency: 'BIF', phone: '+257' },
  { name: 'Cambodia', code: 'KH', currency: 'KHR', phone: '+855' },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', phone: '+237' },
  { name: 'Canada', code: 'CA', currency: 'CAD', phone: '+1' },
  { name: 'Cape Verde', code: 'CV', currency: 'CVE', phone: '+238' },
  { name: 'Central African Republic', code: 'CF', currency: 'XAF', phone: '+236' },
  { name: 'Chad', code: 'TD', currency: 'XAF', phone: '+235' },
  { name: 'Chile', code: 'CL', currency: 'CLP', phone: '+56' },
  { name: 'China', code: 'CN', currency: 'CNY', phone: '+86' },
  { name: 'Colombia', code: 'CO', currency: 'COP', phone: '+57' },
  { name: 'Comoros', code: 'KM', currency: 'KMF', phone: '+269' },
  { name: 'Congo (DRC)', code: 'CD', currency: 'CDF', phone: '+243' },
  { name: 'Congo (Republic)', code: 'CG', currency: 'XAF', phone: '+242' },
  { name: 'Costa Rica', code: 'CR', currency: 'CRC', phone: '+506' },
  { name: 'Croatia', code: 'HR', currency: 'EUR', phone: '+385' },
  { name: 'Cuba', code: 'CU', currency: 'CUP', phone: '+53' },
  { name: 'Cyprus', code: 'CY', currency: 'EUR', phone: '+357' },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK', phone: '+420' },
  { name: 'Denmark', code: 'DK', currency: 'DKK', phone: '+45' },
  { name: 'Djibouti', code: 'DJ', currency: 'DJF', phone: '+253' },
  { name: 'Dominica', code: 'DM', currency: 'XCD', phone: '+1-767' },
  { name: 'Dominican Republic', code: 'DO', currency: 'DOP', phone: '+1-809' },
  { name: 'East Timor', code: 'TL', currency: 'USD', phone: '+670' },
  { name: 'Ecuador', code: 'EC', currency: 'USD', phone: '+593' },
  { name: 'Egypt', code: 'EG', currency: 'EGP', phone: '+20' },
  { name: 'El Salvador', code: 'SV', currency: 'USD', phone: '+503' },
  { name: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', phone: '+240' },
  { name: 'Eritrea', code: 'ER', currency: 'ERN', phone: '+291' },
  { name: 'Estonia', code: 'EE', currency: 'EUR', phone: '+372' },
  { name: 'Eswatini', code: 'SZ', currency: 'SZL', phone: '+268' },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', phone: '+251' },
  { name: 'Fiji', code: 'FJ', currency: 'FJD', phone: '+679' },
  { name: 'Finland', code: 'FI', currency: 'EUR', phone: '+358' },
  { name: 'France', code: 'FR', currency: 'EUR', phone: '+33' },
  { name: 'Gabon', code: 'GA', currency: 'XAF', phone: '+241' },
  { name: 'Gambia', code: 'GM', currency: 'GMD', phone: '+220' },
  { name: 'Georgia', code: 'GE', currency: 'GEL', phone: '+995' },
  { name: 'Germany', code: 'DE', currency: 'EUR', phone: '+49' },
  { name: 'Ghana', code: 'GH', currency: 'GHS', phone: '+233' },
  { name: 'Greece', code: 'GR', currency: 'EUR', phone: '+30' },
  { name: 'Grenada', code: 'GD', currency: 'XCD', phone: '+1-473' },
  { name: 'Guatemala', code: 'GT', currency: 'GTQ', phone: '+502' },
  { name: 'Guinea', code: 'GN', currency: 'GNF', phone: '+224' },
  { name: 'Guinea-Bissau', code: 'GW', currency: 'XOF', phone: '+245' },
  { name: 'Guyana', code: 'GY', currency: 'GYD', phone: '+592' },
  { name: 'Haiti', code: 'HT', currency: 'HTG', phone: '+509' },
  { name: 'Honduras', code: 'HN', currency: 'HNL', phone: '+504' },
  { name: 'Hungary', code: 'HU', currency: 'HUF', phone: '+36' },
  { name: 'Iceland', code: 'IS', currency: 'ISK', phone: '+354' },
  { name: 'India', code: 'IN', currency: 'INR', phone: '+91' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', phone: '+62' },
  { name: 'Iran', code: 'IR', currency: 'IRR', phone: '+98' },
  { name: 'Iraq', code: 'IQ', currency: 'IQD', phone: '+964' },
  { name: 'Ireland', code: 'IE', currency: 'EUR', phone: '+353' },
  { name: 'Israel', code: 'IL', currency: 'ILS', phone: '+972' },
  { name: 'Italy', code: 'IT', currency: 'EUR', phone: '+39' },
  { name: 'Ivory Coast', code: 'CI', currency: 'XOF', phone: '+225' },
  { name: 'Jamaica', code: 'JM', currency: 'JMD', phone: '+1-876' },
  { name: 'Japan', code: 'JP', currency: 'JPY', phone: '+81' },
  { name: 'Jordan', code: 'JO', currency: 'JOD', phone: '+962' },
  { name: 'Kazakhstan', code: 'KZ', currency: 'KZT', phone: '+7' },
  { name: 'Kenya', code: 'KE', currency: 'KES', phone: '+254' },
  { name: 'Kiribati', code: 'KI', currency: 'AUD', phone: '+686' },
  { name: 'Kosovo', code: 'XK', currency: 'EUR', phone: '+383' },
  { name: 'Kuwait', code: 'KW', currency: 'KWD', phone: '+965' },
  { name: 'Kyrgyzstan', code: 'KG', currency: 'KGS', phone: '+996' },
  { name: 'Laos', code: 'LA', currency: 'LAK', phone: '+856' },
  { name: 'Latvia', code: 'LV', currency: 'EUR', phone: '+371' },
  { name: 'Lebanon', code: 'LB', currency: 'LBP', phone: '+961' },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', phone: '+266' },
  { name: 'Liberia', code: 'LR', currency: 'LRD', phone: '+231' },
  { name: 'Libya', code: 'LY', currency: 'LYD', phone: '+218' },
  { name: 'Liechtenstein', code: 'LI', currency: 'CHF', phone: '+423' },
  { name: 'Lithuania', code: 'LT', currency: 'EUR', phone: '+370' },
  { name: 'Luxembourg', code: 'LU', currency: 'EUR', phone: '+352' },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', phone: '+261' },
  { name: 'Malawi', code: 'MW', currency: 'MWK', phone: '+265' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', phone: '+60' },
  { name: 'Maldives', code: 'MV', currency: 'MVR', phone: '+960' },
  { name: 'Mali', code: 'ML', currency: 'XOF', phone: '+223' },
  { name: 'Malta', code: 'MT', currency: 'EUR', phone: '+356' },
  { name: 'Marshall Islands', code: 'MH', currency: 'USD', phone: '+692' },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', phone: '+222' },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', phone: '+230' },
  { name: 'Mexico', code: 'MX', currency: 'MXN', phone: '+52' },
  { name: 'Micronesia', code: 'FM', currency: 'USD', phone: '+691' },
  { name: 'Moldova', code: 'MD', currency: 'MDL', phone: '+373' },
  { name: 'Monaco', code: 'MC', currency: 'EUR', phone: '+377' },
  { name: 'Mongolia', code: 'MN', currency: 'MNT', phone: '+976' },
  { name: 'Montenegro', code: 'ME', currency: 'EUR', phone: '+382' },
  { name: 'Morocco', code: 'MA', currency: 'MAD', phone: '+212' },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', phone: '+258' },
  { name: 'Myanmar', code: 'MM', currency: 'MMK', phone: '+95' },
  { name: 'Namibia', code: 'NA', currency: 'NAD', phone: '+264' },
  { name: 'Nauru', code: 'NR', currency: 'AUD', phone: '+674' },
  { name: 'Nepal', code: 'NP', currency: 'NPR', phone: '+977' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', phone: '+31' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', phone: '+64' },
  { name: 'Nicaragua', code: 'NI', currency: 'NIO', phone: '+505' },
  { name: 'Niger', code: 'NE', currency: 'XOF', phone: '+227' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', phone: '+234' },
  { name: 'North Korea', code: 'KP', currency: 'KPW', phone: '+850' },
  { name: 'North Macedonia', code: 'MK', currency: 'MKD', phone: '+389' },
  { name: 'Norway', code: 'NO', currency: 'NOK', phone: '+47' },
  { name: 'Oman', code: 'OM', currency: 'OMR', phone: '+968' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', phone: '+92' },
  { name: 'Palau', code: 'PW', currency: 'USD', phone: '+680' },
  { name: 'Palestine', code: 'PS', currency: 'ILS', phone: '+970' },
  { name: 'Panama', code: 'PA', currency: 'PAB', phone: '+507' },
  { name: 'Papua New Guinea', code: 'PG', currency: 'PGK', phone: '+675' },
  { name: 'Paraguay', code: 'PY', currency: 'PYG', phone: '+595' },
  { name: 'Peru', code: 'PE', currency: 'PEN', phone: '+51' },
  { name: 'Philippines', code: 'PH', currency: 'PHP', phone: '+63' },
  { name: 'Poland', code: 'PL', currency: 'PLN', phone: '+48' },
  { name: 'Portugal', code: 'PT', currency: 'EUR', phone: '+351' },
  { name: 'Qatar', code: 'QA', currency: 'QAR', phone: '+974' },
  { name: 'Romania', code: 'RO', currency: 'RON', phone: '+40' },
  { name: 'Russia', code: 'RU', currency: 'RUB', phone: '+7' },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', phone: '+250' },
  { name: 'Saint Kitts and Nevis', code: 'KN', currency: 'XCD', phone: '+1-869' },
  { name: 'Saint Lucia', code: 'LC', currency: 'XCD', phone: '+1-758' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', currency: 'XCD', phone: '+1-784' },
  { name: 'Samoa', code: 'WS', currency: 'WST', phone: '+685' },
  { name: 'San Marino', code: 'SM', currency: 'EUR', phone: '+378' },
  { name: 'Sao Tome and Principe', code: 'ST', currency: 'STN', phone: '+239' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', phone: '+966' },
  { name: 'Senegal', code: 'SN', currency: 'XOF', phone: '+221' },
  { name: 'Serbia', code: 'RS', currency: 'RSD', phone: '+381' },
  { name: 'Seychelles', code: 'SC', currency: 'SCR', phone: '+248' },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', phone: '+232' },
  { name: 'Singapore', code: 'SG', currency: 'SGD', phone: '+65' },
  { name: 'Slovakia', code: 'SK', currency: 'EUR', phone: '+421' },
  { name: 'Slovenia', code: 'SI', currency: 'EUR', phone: '+386' },
  { name: 'Solomon Islands', code: 'SB', currency: 'SBD', phone: '+677' },
  { name: 'Somalia', code: 'SO', currency: 'SOS', phone: '+252' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', phone: '+27' },
  { name: 'South Korea', code: 'KR', currency: 'KRW', phone: '+82' },
  { name: 'South Sudan', code: 'SS', currency: 'SSP', phone: '+211' },
  { name: 'Spain', code: 'ES', currency: 'EUR', phone: '+34' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', phone: '+94' },
  { name: 'Sudan', code: 'SD', currency: 'SDG', phone: '+249' },
  { name: 'Suriname', code: 'SR', currency: 'SRD', phone: '+597' },
  { name: 'Sweden', code: 'SE', currency: 'SEK', phone: '+46' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', phone: '+41' },
  { name: 'Syria', code: 'SY', currency: 'SYP', phone: '+963' },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', phone: '+886' },
  { name: 'Tajikistan', code: 'TJ', currency: 'TJS', phone: '+992' },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', phone: '+255' },
  { name: 'Thailand', code: 'TH', currency: 'THB', phone: '+66' },
  { name: 'Togo', code: 'TG', currency: 'XOF', phone: '+228' },
  { name: 'Tonga', code: 'TO', currency: 'TOP', phone: '+676' },
  { name: 'Trinidad and Tobago', code: 'TT', currency: 'TTD', phone: '+1-868' },
  { name: 'Tunisia', code: 'TN', currency: 'TND', phone: '+216' },
  { name: 'Turkey', code: 'TR', currency: 'TRY', phone: '+90' },
  { name: 'Turkmenistan', code: 'TM', currency: 'TMT', phone: '+993' },
  { name: 'Tuvalu', code: 'TV', currency: 'AUD', phone: '+688' },
  { name: 'Uganda', code: 'UG', currency: 'UGX', phone: '+256' },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', phone: '+380' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', phone: '+971' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', phone: '+44' },
  { name: 'United States', code: 'US', currency: 'USD', phone: '+1' },
  { name: 'Uruguay', code: 'UY', currency: 'UYU', phone: '+598' },
  { name: 'Uzbekistan', code: 'UZ', currency: 'UZS', phone: '+998' },
  { name: 'Vanuatu', code: 'VU', currency: 'VUV', phone: '+678' },
  { name: 'Vatican City', code: 'VA', currency: 'EUR', phone: '+379' },
  { name: 'Venezuela', code: 'VE', currency: 'VES', phone: '+58' },
  { name: 'Vietnam', code: 'VN', currency: 'VND', phone: '+84' },
  { name: 'Yemen', code: 'YE', currency: 'YER', phone: '+967' },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', phone: '+260' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', phone: '+263' },
]

export function getCountryFlag(countryName) {
  const country = countries.find(
    c => c.name.toLowerCase() === (countryName || '').toLowerCase()
  )
  if (!country || !country.code) return null
  return country.code
    .toUpperCase()
    .split('')
    .map(char => String.fromCodePoint(0x1F1E6 - 65 + char.charCodeAt(0)))
    .join('')
}

export function getCountryCurrency(countryName) {
  const country = countries.find(
    c => c.name.toLowerCase() === (countryName || '').toLowerCase()
  )
  return country?.currency || 'USD'
}

export function getCountryByCode(code) {
  return countries.find(c => c.code === code)
}

export function searchCountries(query) {
  if (!query) return countries
  const lower = query.toLowerCase()
  return countries.filter(
    c =>
      c.name.toLowerCase().includes(lower) ||
      c.code.toLowerCase().includes(lower)
  )
}
